app.journeyDestination = [
    "Abbey Road",
    "Acton Central",
    "Acton Town",
    "Aldgate",
    "Aldgate East",
    "All Saints",
    "Alperton",
    "Amersham",
    "Anerley",
    "Angel",
    "Archway",
    "Arnos Grove",
    "Arsenal",
    "Baker Street",
    "Balham",
    "Bank",
    "Barbican",
    "Barking",
    "Barkingside",
    "Barons Court",
    "Bayswater",
    "Beckton",
    "Beckton Park",
    "Bermondsey",
    "Bethnal Green",
    "Blackfriars",
    "Blackhorse Road",
    "Blackwall",
    "Bond Street",
    "Borough",
    "Boston Manor",
    "Bounds Green",
    "Bow Church",
    "Bow Road",
    "Brent Cross",
    "Brixton",
    "Brockley",
    "Bromley-By-Bow",
    "Brondesbury",
    "Brondesbury Park",
    "Buckhurst Hill",
    "Burnt Oak",
    "Bushey",
    "Caledonian Road",
    "Caledonian Road & Barnsbury",
    "Camden Road",
    "Camden Town",
    "Canada Water",
    "Canary Wharf",
    "Canning Town",
    "Cannon Street",
    "Canonbury",
    "Canons Park",
    "Carpenders Park",
    "Chalfont & Latimer",
    "Chalk Farm",
    "Chancery Lane",
    "Charing Cross",
    "Chesham",
    "Chigwell",
    "Chiswick Park",
    "Chorleywood",
    "Clapham Common",
    "Clapham High Street",
    "Clapham Junction",
    "Clapham North",
    "Clapham South",
    "Cockfosters",
    "Colindale",
    "Colliers Wood",
    "Covent Garden",
    "Crossharbour",
    "Crouch Hill",
    "Croxley",
    "Crystal Palace",
    "Custom House",
    "Cutty Sark",
    "Cyprus",
    "Dagenham East",
    "Dagenham Heathway",
    "Dalston Junction",
    "Dalston Kingsland",
    "Debden",
    "Denmark Hill",
    "Deptford Bridge",
    "Devons Road",
    "Dollis Hill",
    "Ealing Broadway",
    "Ealing Common",
    "Earl's Court",
    "East Acton",
    "Eastcote",
    "East Finchley",
    "East Ham",
    "East India",
    "East Putney",
    "Edgware",
    "Edgware Road (Bakerloo Line)",
    "Edgware Road (Circle Line)",
    "Elephant & Castle",
    "Elm Park",
    "Elverson Road",
    "Embankment",
    "Emirates Greenwich Peninsula",
    "Emirates Royal Docks",
    "Epping",
    "Euston",
    "Euston Square",
    "Fairlop",
    "Farringdon",
    "Finchley Central",
    "Finchley Road",
    "Finchley Road & Frognal",
    "Finsbury Park",
    "Forest Hill",
    "Fulham Broadway",
    "Gallions Reach",
    "Gants Hill",
    "Gloucester Road",
    "Golders Green",
    "Goldhawk Road",
    "Goodge Street",
    "Gospel Oak",
    "Grange Hill",
    "Great Portland Street",
    "Greenford",
    "Greenwich",
    "Green Park",
    "Gunnersbury",
    "Hackney Central",
    "Hackney Wick",
    "Haggerston",
    "Hainault",
    "Hammersmith (Dist & Pic lines)",
    "Hammersmith (Ham & City Line)",
    "Hampstead",
    "Hampstead Heath",
    "Hanger Lane",
    "Harlesden",
    "Harringay Green Lanes",
    "Harrow & Wealdstone",
    "Harrow-on-the Hill",
    "Hatch End",
    "Hatton Cross",
    "Headstone Lane",
    "Heathrow Terminal 5",
    "Heathrow Terminal 4",
    "Heathrow Terminals 1-3",
    "Hendon Central",
    "Heron Quays",
    "High Barnet",
    "Highbury & Islington",
    "Highgate",
    "High Street Kensington",
    "Hillingdon",
    "Holborn",
    "Holland Park",
    "Holloway Road",
    "Homerton",
    "Honor Oak Park",
    "Hornchurch",
    "Hounslow Central",
    "Hounslow East",
    "Hounslow West",
    "Hoxton",
    "Hyde Park Corner",
    "Ickenham",
    "Imperial Wharf",
    "Island Gardens",
    "Kennington",
    "Kensal Green",
    "Kensal Rise",
    "Kensington (Olympia)",
    "Kentish Town",
    "Kentish Town West",
    "Kenton",
    "Kew Gardens",
    "Kilburn",
    "Kilburn High Road",
    "Kilburn Park",
    "Kingsbury",
    "King's Cross St Pancras",
    "King George V",
    "Knightsbridge",
    "Ladbroke Grove",
    "Lambeth North",
    "Lancaster Gate",
    "Langdon Park",
    "Latimer Road",
    "Leicester Square",
    "Lewisham",
    "Leyton",
    "Leyton Midland Road",
    "Leytonstone",
    "Leytonstone High Road",
    "Limehouse",
    "Liverpool Street",
    "Liverpool Bridge",
    "Liverpool City Airport",
    "Loughton",
    "Maida Vale",
    "Manor House",
    "Mansion House",
    "Marble Arch",
    "Marylebone",
    "Mile End",
    "Mil Hill East",
    "Monument",
    "Moorgate",
    "Moor Park",
    "Morden",
    "Mornington Crescent",
    "Mudchute",
    "Neasden",
    "Newbury Park",
    "New Cross",
    "New Cross Gate",
    "North Acton",
    "North Ealing",
    "Northfields",
    "North Greenwich",
    "North Harrow",
    "Northolt",
    "North Wembley",
    "Northwick Park",
    "Northwood",
    "Northwood Hills",
    "Norwood Junction",
    "Notting Hill Gate",
    "Oakwood",
    "Old Street",
    "Osterley",
    "Oval",
    "Oxford Circus",
    "Paddington",
    "Park Royal",
    "Parsons Green",
    "Peckham Rye",
    "Penge West",
    "Perivale",
    "Piccadilly Circus",
    "Pimlico",
    "Pinner",
    "Plaistow",
    "Pontoon Dock",
    "Poplar",
    "Preston Road",
    "Preston Regent",
    "Pudding Mill Lane",
    "Pudding Bridge",
    "Queensbury",
    "Queen's Park",
    "Queens Road Peckham",
    "Queensway",
    "Ravenscourt Park",
    "Rayners Lane",
    "Rayners",
    "Regent's Park",
    "Richmond",
    "Rickmansworth",
    "Roding Valley",
    "Rotherhithe",
    "Royal Albert",
    "Royal Oak",
    "Royal Victoria",
    "Ruislip",
    "Ruislip Gardens",
    "Ruislip Manor",
    "Russell Square",
    "St James's Park",
    "St John's Wood",
    "St Paul's",
    "St Pancras International",
    "Seven Sisters",
    "Shadwell",
    "Shepherd's Bush (Central Line)",
    "Shepherd's Bush Market",
    "Shoreditch High Street",
    "Sloane Square",
    "Snaresbrook",
    "South Acton",
    "South Ealing",
    "Southfields",
    "Southgate",
    "South Hampstead",
    "South Harrow",
    "South Kensington",
    "South Kenton",
    "South Quay",
    "South Ruislip",
    "South Tottenham",
    "Southwark ",
    "South Wimbledon",
    "South Woodford",
    "Stamford Brook",
    "Stanmore",
    "Star Lane",
    "Stepney Green",
    "Stockwell",
    "Stonebridge Park",
    "Stratford",
    "Stratford High Street",
    "Stratford International",
    "Stratford International DLR",
    "Sudbury Hill",
    "Sudbury Town",
    "Surrey Quays",
    "Swiss Cottage",
    "Sydenham",
    "Temple",
    "Theydon Bois",
    "Tooting Bec",
    "Tooting Broadway",
    "Tottenham Court Road",
    "Tottenham Hale",
    "Totteridge & Whetstone",
    "Tower Gateway",
    "Tower Hill",
    "Tufnell Park",
    "Turnham Green",
    "Turnpike Lane",
    "Upminster",
    "Upminster Bridge",
    "Upney",
    "Upper Holloway",
    "Upton Park",
    "Uxbridge",
    "Vauxhall",
    "Victoria",
    "Walthamstow Central",
    "Walthamstow Queen's Road",
    "Wandsworth Road",
    "Wanstead",
    "Wanstead Park",
    "Wapping",
    "Warren Street",
    "Warwick Avenue",
    "Waterloo",
    "Watford",
    "Watford High Street",
    "Watford Junction",
    "Watford Underground Station",
    "Wembley Central",
    "Wembley Park",
    "West Acton",
    "Westbourne Park",
    "West Brompton",
    "West Croydon",
    "Westferry",
    "West Finchley",
    "West Ham",
    "West Hampstead",
    "West Harrow",
    "West India Quay",
    "West Kensington",
    "Westminster",
    "West Ruislip",
    "West Silvertown",
    "Whitechapel",
    "White City",
    "Willesden Green",
    "Willesden Junction",
    "Wimbledon",
    "Wimbledon Park",
    "Woodford",
    "Woodgrange Park",
    "Wood Green",
    "Wood Lane",
    "Woodside Park",
    "Woolwich Arsenal"
];